# PowerShell Profile - Generated by WSL Ubuntu Setup Script
# Oh My Posh prompt configuration with Catppuccin Mocha theme

# Initialize Oh My Posh with Catppuccin Mocha theme
$OMP_THEME = "$HOME/.config/ohmyposh/catppuccin_mocha.omp.json"
if (Test-Path $OMP_THEME) {
    oh-my-posh init pwsh --config $OMP_THEME | Invoke-Expression
} else {
    Write-Warning "Oh My Posh theme not found at $OMP_THEME"
}

# PSReadLine configuration for better editing experience
if (Get-Module -ListAvailable -Name PSReadLine) {
    Set-PSReadLineOption -EditMode Emacs
    Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
    # PredictionSource only available in PowerShell 7+
    if ($PSVersionTable.PSVersion.Major -ge 7) {
        Set-PSReadLineOption -PredictionSource History
        Set-PSReadLineOption -PredictionViewStyle ListView
    }
}

# Useful aliases (with -Force to override read-only aliases)
Set-Alias -Name ll -Value Get-ChildItem -Force -ErrorAction SilentlyContinue
Set-Alias -Name which -Value Get-Command -Force -ErrorAction SilentlyContinue

# Custom functions
function Get-GitStatus { git status }
Set-Alias -Name gst -Value Get-GitStatus -Force -ErrorAction SilentlyContinue

function Get-GitLog { git log --oneline -10 }
Set-Alias -Name glog -Value Get-GitLog -Force -ErrorAction SilentlyContinue

# WSL integration helpers
function Enter-WSL { wsl.exe }
Set-Alias -Name wsl -Value Enter-WSL -Force -ErrorAction SilentlyContinue
